# Generated by Django 5.0.6 on 2024-06-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('challenge', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
