# Generated by Django 5.0.6 on 2024-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='months_challenge',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
